title: Rails 指南
description: Ruby on Rails 中文指南！
theme: just-the-docs

url: https://docs.rubyist.cn/rails

aux_links:
  『Rubyist 文集』: https://docs.rubyist.cn

callouts:
  work_in_progress:
    color: yellow
    
  note:
    title: "备注"
    color: green
  
  info:
    title: "提示"
    color: blue
