title: Rails 指南
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://docs.rubyist.cn/rails

aux_links:
  Rubyist 文集: https://docs.rubyist.cn

callouts:
  work_in_progress:
    color: yellow

